"""hospital.core — domain primitives, contracts, graph, RNG, events, seam, and KPIs.

This ``__init__`` re-exports **only** the public surface — the symbols downstream
packages are allowed to reuse (doc 00 §3/§4). Everything else is internal and
imported by module path. Keeping this surface small is what keeps the reuse
contract legible and the import-linter contracts meaningful.
"""

from __future__ import annotations

from hospital.core.cost import CostModel, CostRates, Money
from hospital.core.entities import (
    CARE_SLA_BY_ACUITY,
    Bay,
    FloorLayout,
    Patient,
    StaffMember,
    WorkupNeeds,
    Zone,
    care_deadline_for,
)
from hospital.core.enums import (
    ED_ZONE_TYPES,
    WARD_ZONE_TYPES,
    Activity,
    ArrivalMode,
    BayStatus,
    DispositionKind,
    EsiAcuity,
    StaffRole,
    ZoneType,
)
from hospital.core.errors import (
    HospitalCoreError,
    InfeasiblePlan,
    KpiContractError,
    LayoutError,
    SeamViolation,
    UnknownEntity,
    ZeroTimeCycle,
)
from hospital.core.events import (
    BayAssigned,
    BayCleaningCompleted,
    BayCleaningStarted,
    BayRequested,
    DeteriorationDetected,
    DischargeCompleted,
    DischargeStarted,
    DispositionDecided,
    DisruptionInjected,
    DocumentationCompleted,
    DocumentationStarted,
    EmergencyRaised,
    Event,
    EventEnvelope,
    EventLog,
    NurseVisitCompleted,
    NurseVisitStarted,
    PatientArrived,
    PatientMoved,
    ProviderVisitCompleted,
    ProviderVisitStarted,
    StaffIdle,
    StaffMoved,
    TestOrdered,
    TestResulted,
    TriageCompleted,
    TriageStarted,
    VitalsSampled,
)
from hospital.core.graph import RouteEdge, RouteGraph, RouteNode, RoutePath
from hospital.core.ids import (
    BayId,
    NodeId,
    PatientId,
    RunId,
    StaffId,
    TaskId,
    TypedId,
    ZoneId,
)
from hospital.core.kpi import EXTENSIVE_KEYS, KPI_KEYS, STAFF_FRAC_KEYS, KpiVector
from hospital.core.models import FrozenModel
from hospital.core.rng import (
    RandomStreams,
    sample_categorical,
    sample_lognormal,
    sample_poisson_arrivals,
)
from hospital.core.rules import (
    AdmissionRule,
    CapacityRule,
    CompatibilityRule,
    CompiledRules,
    PrecedenceRule,
    Rule,
    SkillRule,
    compile_rules,
    rules_hash,
)
from hospital.core.seam import (
    AWAITING_ADMISSION,
    WAITING_FOR_BAY,
    BayState,
    DecisionInput,
    DecisionResponse,
    ForgetfulMonitor,
    Plan,
    PlanDiff,
    PlanItem,
    RiskAssessment,
    RiskMonitor,
    StaffState,
    TaskSpec,
    WaitingPatient,
    WakeDirective,
)
from hospital.core.time import (
    MICROS_PER_SEC,
    Duration,
    OperatingWeek,
    SimTime,
    TimeWindow,
    hours,
    minutes,
    round_micros,
    seconds,
)
from hospital.core.units import Distance, WalkSpeed, walk_duration
from hospital.core.validation import ValidationContext, Violation, validate
from hospital.core.vitals import (
    NEWS2_PARAMETERS,
    Band,
    News2Result,
    VitalsReading,
    news2_score,
)

__all__ = [
    "AWAITING_ADMISSION",
    "CARE_SLA_BY_ACUITY",
    "ED_ZONE_TYPES",
    "EXTENSIVE_KEYS",
    "KPI_KEYS",
    "MICROS_PER_SEC",
    "NEWS2_PARAMETERS",
    "STAFF_FRAC_KEYS",
    "WAITING_FOR_BAY",
    "WARD_ZONE_TYPES",
    "Activity",
    "AdmissionRule",
    "ArrivalMode",
    "Band",
    "Bay",
    "BayAssigned",
    "BayCleaningCompleted",
    "BayCleaningStarted",
    "BayId",
    "BayRequested",
    "BayState",
    "BayStatus",
    "CapacityRule",
    "CompatibilityRule",
    "CompiledRules",
    "CostModel",
    "CostRates",
    "DecisionInput",
    "DecisionResponse",
    "DeteriorationDetected",
    "DischargeCompleted",
    "DischargeStarted",
    "DispositionDecided",
    "DispositionKind",
    "DisruptionInjected",
    "Distance",
    "DocumentationCompleted",
    "DocumentationStarted",
    "Duration",
    "EmergencyRaised",
    "EsiAcuity",
    "Event",
    "EventEnvelope",
    "EventLog",
    "FloorLayout",
    "ForgetfulMonitor",
    "FrozenModel",
    "HospitalCoreError",
    "InfeasiblePlan",
    "KpiContractError",
    "KpiVector",
    "LayoutError",
    "Money",
    "News2Result",
    "NodeId",
    "NurseVisitCompleted",
    "NurseVisitStarted",
    "OperatingWeek",
    "Patient",
    "PatientArrived",
    "PatientId",
    "PatientMoved",
    "Plan",
    "PlanDiff",
    "PlanItem",
    "PrecedenceRule",
    "ProviderVisitCompleted",
    "ProviderVisitStarted",
    "RandomStreams",
    "RiskAssessment",
    "RiskMonitor",
    "RouteEdge",
    "RouteGraph",
    "RouteNode",
    "RoutePath",
    "Rule",
    "RunId",
    "SeamViolation",
    "SimTime",
    "SkillRule",
    "StaffId",
    "StaffIdle",
    "StaffMember",
    "StaffMoved",
    "StaffRole",
    "StaffState",
    "TaskId",
    "TaskSpec",
    "TestOrdered",
    "TestResulted",
    "TimeWindow",
    "TriageCompleted",
    "TriageStarted",
    "TypedId",
    "UnknownEntity",
    "ValidationContext",
    "Violation",
    "VitalsReading",
    "VitalsSampled",
    "WaitingPatient",
    "WakeDirective",
    "WalkSpeed",
    "WorkupNeeds",
    "ZeroTimeCycle",
    "Zone",
    "ZoneId",
    "ZoneType",
    "care_deadline_for",
    "compile_rules",
    "hours",
    "minutes",
    "news2_score",
    "round_micros",
    "rules_hash",
    "sample_categorical",
    "sample_lognormal",
    "sample_poisson_arrivals",
    "seconds",
    "validate",
    "walk_duration",
]
